//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThemeParkManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RIDE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RIDE()
        {
            this.MAINTENANCEs = new HashSet<MAINTENANCE>();
            this.GUEST_RIDES = new HashSet<GUEST_RIDES>();
            this.RIDES_STAFF = new HashSet<RIDES_STAFF>();
        }
    
        public int RideID { get; set; }
        public string RideName { get; set; }
        public decimal RidePrice { get; set; }
        public bool IsOutside { get; set; }
        public Nullable<int> RainOutCount { get; set; }
        public bool IsOpen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAINTENANCE> MAINTENANCEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GUEST_RIDES> GUEST_RIDES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RIDES_STAFF> RIDES_STAFF { get; set; }
    }
}
