//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThemeParkManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RIDE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RIDE()
        {
            this.MAINTENENCEs = new HashSet<MAINTENENCE>();
        }
    
        public int RideID { get; set; }
        public string RideName { get; set; }
        public Nullable<decimal> RidePrice { get; set; }
        public Nullable<bool> IsOutside { get; set; }
        public Nullable<int> RainOutCount { get; set; }
        public Nullable<bool> IsOpen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAINTENENCE> MAINTENENCEs { get; set; }
    }
}
