//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThemeParkManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKET
    {
        public int TicketID { get; set; }
        public string TicketType { get; set; }
        public decimal TicketPrice { get; set; }
        public System.DateTime datePurchased { get; set; }
    }
}
